# Sample config file.. This is a distribution file for you to copy and edit away :)
# TODO put here some nice Kubernetes like thingies so I look intelligent :)
ConfigVersion: 1.0
Config:
  AdditionalMountDirs:
    - ~/disks/
    - ~/git/storazzo/var/test/disks/
    - /wrong/on/purpose/ 
    - ~/sbobinamenti/ # Italian for "temporary storage parking" => hence the English "to sbobinate"
  DefaultFolder: ~/.storazzo/ 
  Backends:
    GoogleCloudStorage:
      # Bad idea to have BucketName and BucketDir
      # Since you can have both in one :) 
      #BucketName: gs://palladius-backup/
      #BucketDir: storazzo/
      ProjectId: YOUR-PROJECT-ID
      BucketPaths: 
      - path: gs://my-local-backup/storazzo/backups/
        name: My First Backup
      - path: gs://my-other-bucket/
        name: My Other Backup
