

ricdisk-magic-local:
	bundle exec bin/ricdisk-magic .

watch-ricdisk-magic-local:
	watch bundle exec bin/ricdisk-magic .

watch-ricdisk-magic-local-etc-readonly:
	watch bundle exec bin/ricdisk-magic /etc///
